trainer:
  logger:
   class_path: lightning.pytorch.loggers.wandb.WandbLogger
   init_args:
     resume: allow
     name: "segmentation"
     project: "vitin1k"
  devices: 1
  num_nodes: 1
  max_steps: 40000
  val_check_interval: 4000
  check_val_every_n_epoch: null
model:
  class_path: training.segmentation.Segmentation
  init_args:
    network:
      class_path: models.segmentation.vit_lightweight_head.VITLightweightHead
      init_args:
        model_name: "dinov2_vitb14"
        num_classes: 19
data:
  class_path: datasets.uda_multitrain_multival_datamodule2.UDAMultiTrainMultiValDataModule2
  init_args:
    batch_size: 2
    train_num_workers: 8
    img_size: 1024
    sources: ["cityscapes"]